### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by Zaldor** [verginer/bnb_scrapy_tutorial#1]
Could anybody confirm that this script is still functioning correctly?
Thanks

**Comment by verginer** [comment]
Updated the `xpath` query now it works again. 
Airbnb changed their css on the landing page.

**Comment by gesteves91** [comment]
Hi Lucca, really nice work. Could you confirm if the script still works? Airbnb seems to have changed the css one more time, and I'm getting 0 bytes even cloning your repo.
Thanks,

**Comment by verginer** [comment]
I have fixed it on my end with the latest commit if you could confirm that it works also for you that would be great.

**Comment by verginer** [comment]
Ok I have found the issue, airbnb serves a different site now sometimes, where `page=` is replaced by `section_offset=`, but it only affects the .com domain from certain countries.

However I don't have time right now to fix it considering all the possible permutations.
If you would like to work on a possible solution that would also be great.

**Comment by Michaelp86** [comment]
Hi Lucca,

It worked well few days ago but I think there is a new problem for finding the last pages.
```python
def last_pagenumer_in_search(self, response):
        try:  # to get the last page number
            last_page_number = int(response
                                   .xpath('//ul[@class="list-unstyled"]/li[last()-1]/a/@href')
                                   .extract()[0]
                                   .split('page=')[1]
                                   )
            return last_page_number
```
In the script website it is still at the `li[last()-1]/a/@href` but there is no more ('page='). 
If someone could have a look. I don't find how to fix it.
Cheers,

Michael

**Comment by toxydose** [comment]
I found that the value 'page=' is changed to the value 'section_offset=' But this value is not presented on the first page, the second page has a value section_offset=1, and the 17-th page section_offset=16

**Comment by verginer** [comment]
This has been addressed in #4 and solved #6

**Comment by aabid0193** [comment]
possible to get another update, as I am getting 0 bytes now from this

**Comment by aabid0193** [comment]
Airbnb seems to have changed the css one more time, and I'm getting 0 bytes even cloning your repo.
This is incredible work though, 
Thanks

**Comment by verginer** [comment]
Hi @aabid0193, thanks glad you like it. Currently to get this version of the code to work would require to rewrite it from the ground up since the data is no longer served as it was a year ago. In the README.md I have a link to an up to dare extension of this code. Wish you best of luck with scraping 😉

**Comment by aabid0193** [comment]
Thank you!
