### ISSUE TITLE
Plotting the Data on the Map

### ISSUE THREAD

**Issue by ricerd95** [verginer/bnb_scrapy_tutorial#2]
Hi Luca,

May I know how do you done the plotting the data on the map?
I can't really get the idea or even the way to do so.

Thank you

**Comment by verginer** [comment]
Hi ricerd95,

It depends what you want to do. 
For the picture you see in the post I used QGis and imported the csv with latitude and longitude values.

If you are looking to simply put some markers on the map I suggest you try [folium](https://github.com/python-visualization/folium) in conjuction with a Jupyter notebook.

As for the lat/lng you can find those in the header of the html page served by airbnb

**Comment by ricerd95** [comment]
Hi verginer,

Ya I am looking for as what you had in your post.
For the lat/lng, is it meaning I need to manually search for it and save it into a csv file and create the map? Or is there any avaible coding to assist me in retrieve those value?

Thank you.

**Comment by verginer** [comment]
The post describes how to do exactly that ( automatically download data from AirBnb)
you just have to change i guess two lines and you can get as many lat/lng observations as you want.

Hope this helps

**Comment by ricerd95** [comment]
I created this 2 lines of code in json array but it does not seem working

```
item['h_latitude'] = airbnb_json['latitude']
item['h_longitude'] = airbnb_json['longitude']
```

**Comment by verginer** [comment]
That is because the latitude and longitude information is NOT in the json file, it is in the head portion of the html.
Just to get you started, you will need to extract the information that will look something like this in the Airbnb page
```html
<meta property="airbedandbreakfast:location:latitude" content="-8.499051976213554">
<meta property="airbedandbreakfast:location:longitude" content="114.96453561632455">
```
And this you can get with an XPath expression that selects the `content` attribute of the `meta` tag with a `property` equal to `"airbedandbreakfast:location:longitude"`.

As mentioned in the article if you need help with XPath look at [this tutorial](http://www.w3schools.com/xml/xpath_intro.asp)

**Comment by ricerd95** [comment]
Is it like this?

`json_array = response.xpath('//meta[@property="airbedandbreakfast:location"]/@content').extract()`

By the way how I going to put 2 xpath together?

**Comment by verginer** [comment]
```python
longitude = response.xpath('//meta[@property="airbedandbreakfast:location:longitude"]/@content').extract()
latitude = response.xpath('//meta[@property="airbedandbreakfast:location:latitude"]/@content').extract()

coord = (float(latitude), float(longitude))
```

Hope this helps, but you will have to experiment yourself

**Comment by ricerd95** [comment]
Thanks, it woked
