### ISSUE TITLE
bnbtutorial.items issue

### ISSUE THREAD

**Issue by toxydose** [verginer/bnb_scrapy_tutorial#5]
I just cloned your repo, but the script could not find the items

Traceback (most recent call last):
  File "bnbspider.py", line 4, in <module>
    from bnbtutorial.items import BnbtutorialItem
ImportError: No module named bnbtutorial.items

**Comment by verginer** [comment]
Thanks, the tip has been very helpful! 👍

**Comment by toxydose** [comment]
The issue appears again. Maybe I am doing something incorrect?

**Comment by verginer** [comment]
How do you call scrapy? In which directory are you when you execute the command? Did you clone the repo or did you write it yourself?

**Comment by toxydose** [comment]
I cloned the repo.
cd bnb_scrapy_tutorial/bnbtutorial/spiders/
python bnbspider.py

**Comment by verginer** [comment]
No you don't execute it like that. If you have a look at the blog post I link to in the readme http://www.verginer.eu/blog/web-scraping-airbnb/
you will see how to correctly start scrapy

**Comment by toxydose** [comment]
@verginer thank you for your feedback!
